apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: spring-app
  labels:
    app.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/zrob/spring-app
      ref:
        branch: main
