apiVersion: kontinue.io/v1alpha1
kind: Workload
metadata:
  name: sample-app-java
  labels:
    app.tanzu.vmware.com/workload-type: thing
spec:
  source:
    git:
      url: https://github.com/spring-projects/spring-petclinic
      ref:
        branch: main
